stages:
  - lint
  - deploy

vue-cli-service-lint:
  stage: lint
  script:
    - touch backend.env
    - echo MYSQL_DATABASE=$MYSQL_DATABASE > backend.env && echo MYSQL_USER=$MYSQL_USER >> backend.env
    - echo MYSQL_PASSWORD=$MYSQL_PASSWORD >> backend.env && echo SAULT=$SAULT >> backend.env
    - echo FRONTEND_HOST=$FRONTEND_HOST >> backend.env && echo BACKEND_HOST=$BACKEND_HOST >> backend.env
    - touch db.env
    - echo MYSQL_DATABASE=$MYSQL_DATABASE > db.env && echo MYSQL_USER=$MYSQL_USER >> db.env
    - echo MYSQL_PASSWORD=$MYSQL_PASSWORD >> db.env && echo LANG=$LANG >> db.env
    - echo MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD >> db.env
    - touch frontend.env
    - echo BACKEND_HOST=$BACKEND_HOST_FOR_FRONTEND_DEV > frontend.env
    - docker-compose up -d --build
    - docker-compose exec frontend npm run lint
  after_script:
    - docker-compose down

deploy-to-prod:
  stage: deploy
  script:
    - touch backend.env
    - echo MYSQL_DATABASE=$MYSQL_DATABASE > backend.env && echo MYSQL_USER=$MYSQL_USER >> backend.env
    - echo MYSQL_PASSWORD=$MYSQL_PASSWORD >> backend.env && echo SAULT=$SAULT >> backend.env
    - echo FRONTEND_HOST=$FRONTEND_HOST_PROD >> backend.env && echo BACKEND_HOST=$BACKEND_HOST >> backend.env
    - touch db.env
    - echo MYSQL_DATABASE=$MYSQL_DATABASE > db.env && echo MYSQL_USER=$MYSQL_USER >> db.env
    - echo MYSQL_PASSWORD=$MYSQL_PASSWORD >> db.env && echo LANG=$LANG >> db.env
    - echo MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD >> db.env
    - docker-compose -f docker-compose.prod.yml down
    - docker-compose -f docker-compose.prod.yml up -d --build
  when: manual