version: '3'

services:
  proxy:
    build: ./
    restart: always
    ports:
      - '80:80'
    depends_on:
      - backend
      - frontend
  frontend:
    build: ./frontend
    restart: always
    env_file:
      - ./frontend.env
    depends_on:
      - backend
  backend:
    build: ./backend
    restart: always
    volumes:
      - srv_images:/srv/work_images
    depends_on:
      - database
    env_file:
      - ./backend.env
  database:
    image: 'mysql:8.0'
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    env_file:
      - ./db.env
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080

volumes:
  mysql_data:
  srv_images: