version: '3'

services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - '9000:9000'
  backend:
    build: ./backend
    restart: always
    ports:
      - '80:80'
  database:
    image: 'mysql:8.0'
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql_data: