version: '3'

services:
  frontend:
    build: 
      context: ./frontend
    restart: always
    ports:
      - '80:80'
  backend:
    build: ./backend
    restart: always
    volumes:
      - srv_images:/srv/work_images
    ports:
      - '8082:8082'
    depends_on:
     - database
    env_file:
      - ./backend.env
  database:
    image: 'mysql:8.0'
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    env_file:
      - ./db.env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql_data:
  srv_images: