version: '3'

services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
  backend:
    build: ./backend
    restart: always
    volumes:
      - ./backend:/srv
    ports:
      - '80:80'
    depends_on:
     - database
    env_file:
      - ./common_db.env
  database:
    image: 'mysql:8.0'
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    env_file:
      - ./root_db.env
      - ./common_db.env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql_data: